Repository webkom/admissions, pull requests merged in 2022-09, with the labels that each got.

#566 Move initialization of calcTimeDiff method before usage
  frontend/src/components/AdmissionCountDown/index.jsx
Labels: bug-fix, approved, ready-to-merge

#546 Split receipt page into separate component
  frontend/src/containers/GroupApplication/Application.jsx
  frontend/src/containers/GroupApplication/index.jsx
  frontend/src/routes/ApplicationForm/FormStructure.jsx
  frontend/src/routes/ApplicationForm/FormStructureStyle.jsx
  frontend/src/routes/ApplicationForm/PhoneNumberField.jsx
  frontend/src/routes/ApplicationForm/PriorityTextField.jsx
  frontend/src/routes/ApplicationForm/index.jsx
  frontend/src/routes/ApplicationPortal.jsx
  frontend/src/routes/ReceiptForm/FormStructure.jsx
  frontend/src/routes/ReceiptForm/index.jsx
  frontend/src/utils/draftHelper.js
Labels: enhancement, approved, ready-to-merge

#571 Remove copy webpack-stats from dockerfile
  Dockerfile
Labels: bug-fix

#572 Compile production dependencies
  requirements/production.txt
Labels: small-fix

#574 Convert allowed hosts variable to list for Django v4
  committee_admissions/settings/production.py
Labels: bug-fix

#573 Remove unused moment deps
  package.json
  yarn.lock
Labels: small-fix, flawless

#576 Set path to vite bundles to the correct directory
  committee_admissions/settings/base.py
  committee_admissions/settings/production.py
Labels: approved
