Repository webkom/admissions, pull requests merged in 2023-04, with the labels that each got.

#877 Complete manage-admissions endpoint
  admissions/admissions/constants.py
  admissions/admissions/migrations/0007_admission_created_by_alter_admission_description_and_more.py
  admissions/admissions/models.py
  admissions/admissions/permissions.py
  admissions/admissions/serializers.py
  admissions/admissions/views.py
  admissions/oauth.py
  admissions/templates/index.html
  admissions/urls.py
  frontend/src/query/hooks.ts
  frontend/src/query/mutations.ts
  frontend/src/routes/LandingPage/LandingPageSkeleton.tsx
  frontend/src/routes/ManageAdmissions/CreateAdmission.tsx
  frontend/src/routes/ManageAdmissions/components/GroupSelector.tsx
  frontend/src/routes/ManageAdmissions/components/NavBar.tsx
  frontend/src/routes/ManageAdmissions/index.tsx
Labels: new-feature, approved

#981 Make create-application use the correct admisison
  admissions/admissions/serializers.py
  admissions/admissions/views.py
  frontend/src/routes/LandingPage/Admission.tsx
  frontend/src/types.ts
Labels: bug, review-needed

#983 Delete and view application after deadline
  frontend/src/routes/LandingPage/Admission.tsx
  frontend/src/routes/ReceiptForm/FormStructure.tsx
Labels: frontend, bug-fix, approved

#982 Update README with poetry instructions and fix typos
  README.md
  admissions/settings/example.env
  frontend/src/routes/AdminPage/form.tsx
Labels: review-needed

#1011 Cleanup django models
  admissions/admissions/factories.py
  admissions/admissions/migrations/0008_admissiongroup_and_more.py
  admissions/admissions/models.py
  admissions/admissions/serializers.py
  admissions/admissions/tests/test_api.py
  admissions/utils/management/commands/create_admission.py
  frontend/src/query/mutations.ts
  frontend/src/routes/AdminPageAbakusLeaderView/index.tsx
  frontend/src/routes/LandingPage/Admission.tsx
  frontend/src/routes/ManageAdmissions/CreateAdmission.tsx
  frontend/src/types.ts
Labels: enhancement, approved, review-needed, technical-debt

#1015 Add logo to django assets and update og:image
  admissions/assets/og_logo.png
  admissions/templates/index.html
Labels: bug-fix, approved

#1014 Convert from using id to slug for admission
  admissions/admissions/migrations/0009_admission_slug.py
  admissions/admissions/models.py
  admissions/admissions/serializers.py
  admissions/admissions/tests/test_api.py
  admissions/admissions/views.py
  admissions/urls.py
  frontend/src/components/Application/DeleteApplication/index.tsx
  frontend/src/components/NavBar/index.tsx
  frontend/src/containers/UserApplicationAdminView/index.tsx
  frontend/src/index.tsx
  frontend/src/query/hooks.ts
  frontend/src/query/mutations.ts
  frontend/src/routes/AdminPage/index.tsx
  frontend/src/routes/AdminPageAbakusLeaderView/index.tsx
  frontend/src/routes/ApplicationForm/FormStructure.tsx
  frontend/src/routes/ApplicationForm/ToggleGroups.tsx
  frontend/src/routes/ApplicationForm/index.tsx
  frontend/src/routes/ApplicationPortal.tsx
  frontend/src/routes/GroupsPage/index.tsx
  frontend/src/routes/LandingPage/Admission.tsx
  frontend/src/routes/ManageAdmissions/CreateAdmission.tsx
  frontend/src/routes/ManageAdmissions/components/NavBar.tsx
  frontend/src/routes/ManageAdmissions/index.tsx
  frontend/src/routes/ReceiptForm/FormStructure.tsx
  frontend/src/routes/ReceiptForm/index.tsx
  frontend/src/types.ts
Labels: enhancement, review-needed
